<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Login page</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
</head>
<body>
<h3 align="center">REGISTRATION PAGE </h3>
<p></p>
<div class="container" align="center">
  <strong>
<form action="/register" method="post">
  <div class="mb-3" c>

    <label for="exampleInputEmail1" class="form-label" >Please enter your email address: </label>
    <input name="email" type="email" class="form-control" id="exampleInputEmail1" style="width:300px;height:35px" aria-describedby="emailHelp">
  </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Please enter your password:</label>
    <input name="password" type="password" class="form-control" style="width:300px;height:35px" id="exampleInputPassword1">
  </div>
  <button type="submit" class="btn btn-primary" style="width:137px">SUBMIT</button>

</form>
  </strong>
</div>
<p></p>
<div class="container" align="center">
  <label>Already registered?</label>
  <p></p>

  <a href="/login" class="btn btn-dark" style="width:137px">LOG IN</a>
</div>
<#if errorMessage??>
<p></p>
<p align="center"><strong>${errorMessage}</strong></p>
</#if>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
</body>
</html>
